#!/bin/bash

shopt -u dotglob

if [[ $# -ne 1 ]]; then
    echo "Error: provide command: --update-repo or --update-system"
    exit -1
fi

DOTFILES="$HOME/dev/dotfiles"

case $1 in
--update-repo)
    # copy gnupg related files
    cp -r ~/.gnupg/gpg-agent.conf ~/.gnupg/gpg.conf "$DOTFILES"/.gnupg
    # copy .bashrc and related stuff
    cp -r ~/bin ~/.bash ~/.bashrc ~/.bash_logout ~/.bash_profile ~/.xinitrc "$DOTFILES"/shell

    # copy emacs directories
    rm -rf *.session
    cp -r ~/.emacs ~/.emacscore "$DOTFILES"/emacs

    # copy i3 stuff
    cp -r ~/.i3/* "$DOTFILES"/i3

    # copy terminator stuff
    cp -r ~/.config/terminator/config  "$DOTFILES"/terminator

    # copy other dotfiles
    cp -r ~/.gdbinit "$DOTFILES"
    cp -r ~/.gitconfig "$DOTFILES"/git
    cp -r ~/.gitignore_global "$DOTFILES"/git
    cp -r ~/.tmux.conf "$DOTFILES"
    cp -r ~/.inputrc "$DOTFILES"
    ;;
--update-system)
    # copy gnupg related files
    cp -r "$DOTFILES"/.gnupg/*.conf ~/.gnupg/

    # copy standard dtofiles
    cp -r .tmux.conf .gdbinit .inputrc "$DOTFILES/git/." "$HOME"

    # copy emacs files
    rm -rf "$HOME"/{.emacs,.emacscore}
    cp -r emacs/.emacs emacs/.emacscore "$HOME"
    
    # copy i3 stuff
    cp -r "$DOTFILES"/i3/* "$HOME/.i3"

    # copy terminator stuff
    cp -r "$DOTFILES"/terminator/* "$HOME/.config/terminator"

    # Copy scripts to $HOME directory
    cp -r "$DOTFILES"/shell/. "$DOTFILES/shell/bin" $HOME

    # install bin scripts
    "$HOME/bin/installScripts"
    ;;
*)
    echo "Error: provide command: --update-repo or --update-system"
    exit -1
    ;;
esac

echo -e "\e[32mDone.\e[39m"
