#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

shopt -u dotglob

# Check command line arguments
if [[ $# -ne 1 ]]; then
    echo "Error: provide command: --update-repo or --update-system"
    exit -1
fi

# Path to the dotfiles repository
DOTFILES="$HOME/dev/dotfiles"

# Path to the Firefox profile directory
MOZILA_PROFILE_DIR=$(
    awk '/^\[Profile[0-9]+\]$/ { section = $0 }
         /^Default=1$/ { print section }
         /^Path=/ && section { path = $0 }
         /^Default=1$/ && path { print path; exit }' ~/.mozilla/firefox/profiles.ini | grep '^Path=' | cut -d= -f2)
MOZILA_PROFILE_DIR="$HOME/.mozilla/firefox/$MOZILA_PROFILE_DIR"
# Path to the Firefox user themes
MOZILA_PROFILE_CSS_DIR="$MOZILA_PROFILE_DIR"/chrome
# Path to the Firefox extensions directory
MOZILA_EXTENSIONS_DIR="$MOZILA_PROFILE_DIR"/extensions

case $1 in
--update-repo)
    # Copy firefox settings
    test -f "$MOZILA_PROFILE_DIR"/user.js && cp -r "$MOZILA_PROFILE_DIR"/user.js "$DOTFILES"/firefox
    test -f "$MOZILA_PROFILE_CSS_DIR"/userChrome.css && cp -r "$MOZILA_PROFILE_CSS_DIR"/userChrome.css "$DOTFILES"/firefox/css

    # Copy mail scripts and configuration
    test -f "$HOME"/.neomutrc && cp -r "$HOME"/.neomutrc "$DOTFILES"/mail
    test -f "$HOME"/.offlineimaprc && cp -r "$HOME"/.offlineimaprc "$DOTFILES"/mail
    test -d "$HOME"/.mail && cp -r "$HOME"/.mail "$DOTFILES"/mail

    # Copy .bashrc and related stuff
    test -d "$HOME"/bin && cp -r "$HOME"/bin "$DOTFILES"/shell
    test -d "$HOME"/.bash && cp -r "$HOME"/.bash "$DOTFILES"/shell
    test -f "$HOME"/.bashrc && cp -r "$HOME"/.bashrc "$DOTFILES"/shell
    test -f "$HOME"/.bash_logout && cp -r "$HOME"/.bash_logout "$DOTFILES"/shell
    test -f "$HOME"/.bash_profile && cp -r "$HOME"/.bash_profile "$DOTFILES"/shell

    # Copy emacs directories
    test -f "$HOME"/.emacs && cp -r "$HOME"/.emacs "$DOTFILES"/emacs
    test -d "$HOME"/.emacscore && cp -r "$HOME"/.emacscore "$DOTFILES"/emacs

    # Copy i3 stuff
    test -d "$HOME"/.i3 && cp -r "$HOME"/.i3/* "$DOTFILES"/i3
    # Copy sway stuff
    test -d "$HOME"/.sway && cp -r "$HOME"/.sway/* "$DOTFILES"/sway
    # Copy hyprland stuff
    test -d "$HOME"/.config/hypr && cp -r "$HOME"/.config/hypr "$DOTFILES"/hyprland
    test -d "$HOME"/.config/wofi && cp -r "$HOME"/.config/wofi "$DOTFILES"/hyprland
    test -d "$HOME"/.config/waybar && cp -r "$HOME"/.config/waybar "$DOTFILES"/hyprland

    # Copy lisp/sbcl configuration
    test -r "$HOME"/.sbclrc && cp -r "$HOME"/.sbclrc "$DOTFILES"/dev/

    # Copy zig/zls related files
    test -r "$HOME"/.config/zls.json && cp -r "$HOME"/.config/zls.json "$DOTFILES"/.config

    # Copy gnupg related files
    test -r "$HOME"/.gnupg/public.key && cp -r "$HOME"/.gnupg/public.key "$DOTFILES"/.gnupg
    test -r "$HOME"/.gnupg/gpg-agent.conf && cp -r "$HOME"/.gnupg/gpg-agent.conf "$DOTFILES"/.gnupg
    test -r "$HOME"/.gnupg/gpg.conf && cp -r "$HOME"/.gnupg/gpg.conf "$DOTFILES"/.gnupg

    # Copy terminator stuff
    test -r "$HOME"/.config/terminator/config && cp -r "$HOME"/.config/terminator/config  "$DOTFILES"/terminator

    # Copy X files
    test -r "$HOME"/.Xresources && cp -r "$HOME"/.Xresources "$DOTFILES"/system/
    test -r "$HOME"/.xinitrc && cp -r "$HOME"/.xinitrc "$DOTFILES"/system/

    # Copy other dotfiles
    test -r "$HOME"/.gdbinit && cp -r "$HOME"/.gdbinit "$DOTFILES"
    test -r "$HOME"/.gitconfig && cp -r "$HOME"/.gitconfig "$DOTFILES"/git
    test -r "$HOME"/.gitignore_global && cp -r "$HOME"/.gitignore_global "$DOTFILES"/git
    test -r "$HOME"/.tmux.conf && cp -r "$HOME"/.tmux.conf "$DOTFILES"
    test -r "$HOME"/.inputrc && cp -r "$HOME"/.inputrc "$DOTFILES"
    test -r "$HOME"/.pythonrc && cp -r "$HOME"/.pythonrc  "$DOTFILES"

    # Copy zed cconfiguration
    test -r "$HOME"/.config/zed/settings.json && cp -r "$HOME"/.config/zed/settings.json ./zed
    test -r "$HOME"/.config/zed/keymap.json && cp -r "$HOME"/.config/zed/keymap.json ./zed

    # Copy prettier configuration
    test -r "$HOME"/.prettierrc && cp -r "$HOME"/.prettierrc .
    ;;
--update-system)
    # Copy zed configuration
    mkdir -p "$HOME"/.config/zed
    cp -r ./zed/* "$HOME"/.config/zed

    # Copy prettier configuratoin
    cp -r .prettierrc "$HOME"/

    # Copy mail scripts and configuration
    cp -r "$DOTFILES"/mail/.mail "$HOME"/
    cp -r "$DOTFILES"/mail/.neomutrc "$HOME"/
    cp -r "$DOTFILES"/mail/.offlineimaprc "$HOME"/
    sudo cp -r "$DOTFILES"/mail/email "$DOTFILES"/mail/sync-email /usr/local/bin

    # Copy lisp/sbcl configuration
    cp -r "$DOTFILES"/dev/.sbclrc "$HOME"/.sbclrc

    # Copy zig/zls related files
    cp -r "$DOTFILES"/.config/zls.json "$HOME"/.config/

    # Copy gnupg related files
    cp -r "$DOTFILES"/.gnupg/*.conf "$DOTFILES"/.gnupg/public.key "$HOME"/.gnupg/

    # Copy standard dtofiles
    cp -r .tmux.conf .gdbinit .inputrc .pythonrc "$DOTFILES/git/." "$HOME"/

    # Copy emacs files
    rm -rf "$HOME"/{.emacs,.emacscore}
    cp -r emacs/.emacs emacs/.emacscore "$HOME"/

    # Copy i3 stuff
    mkdir -p "$HOME"/.i3
    cp -r "$DOTFILES"/i3/* "$HOME"/.i3

    # Copy sway stuff
    mkdir -p "$HOME"/.sway
    cp -r "$DOTFILES"/sway/* "$HOME"/.sway

    # Copy hyprland stuff
    mkdir -p "$HOME"/.config/{hypr,wofi,waybar}
    cp -r "$DOTFILES"/hyprland/hypr/* "$HOME"/.config/hypr/
    cp -r "$DOTFILES"/hyprland/wofi/* "$HOME"/.config/wofi/
    cp -r "$DOTFILES"/hyprland/waybar/* "$HOME"/.config/waybar/

    # Copy terminator stuff
    mkdir -p "$HOME"/.config/terminator && cp -r "$DOTFILES"/terminator/* "$HOME"/.config/terminator

    # Copy scripts to home directory
    cp -r "$DOTFILES"/shell/. "$DOTFILES/shell/bin" "$HOME"/

    # Copy system (per-user) files
    cp -r "$DOTFILES"/system/{.Xresources,.xinitrc} "$HOME"/

    # Copy firefox settings
    cp -r "$DOTFILES"/firefox/user.js "$MOZILA_PROFILE_DIR"/
    mkdir -p "$MOZILA_PROFILE_CSS_DIR"/ && cp -r "$DOTFILES"/firefox/css/*.css "$MOZILA_PROFILE_CSS_DIR"/

    # Install bin scripts
    "$HOME"/bin/installScripts
    ;;
*)
    echo "Error: provide command: --update-repo or --update-system"
    exit -1
    ;;
esac

echo -e "\e[32mDone.\e[39m"
