name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [ccl, sbcl]
        os: [ubuntu-latest]
        emacs_version: [24-5, 25-3, 26-3, snapshot]
      fail-fast: false
    steps:

    - uses: cachix/install-nix-action@v12
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - run: nix-env -i ${{ matrix.lisp }}
    - run: make LISP="${{ matrix.lisp }}" check
