#!/bin/bash

#
# Additional bash completions
#

# git completion
if [[ -f /etc/bash_completion.d/git-completion.bash ]];
then
    source /usr/share/bash-completion/completions/git
fi

# kubernetes auto completion
if [[ -f ~/.conf/kube-autocomplete.sh ]];
then
  source ~/.conf/kube-autocomplete.sh
fi

