#!/bin/bash

#
# elixir
#
export PATH="$PATH:$WORK/elixir/bin"

#
# docker
#
export PATH="$PATH:$DEV/docker/bundles/latest/binary"

#
# phabricator, tetrapak and rebar
#
export PATH="$PATH:$WORK/util/arcanist/bin/"
export PATH="$PATH:$WORK/tetrapak/bin/"
export PATH="$PATH:$WORK/rebar/"

#
# LD
#
export LD_LIBRARY_PATH=""
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME_HDD/usr/local/pgsql/lib/"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:deps/dnssd/priv"

export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH

#
# Kernel and C dev, systemd
#
export PATH=$PATH:$KERNEL_DEV/tools/perf/
export PATH=$PATH:/usr/lib/systemd/

#
# Databases
#
export PATH=$PATH:$HOME_HDD/usr/local/pgsql/bin/

# golang
export GOROOT=$DEV/golang/go
export GOPATH=$DEV/dev/golang
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin

# less
export LESSHISTFILE="/dev/null"

#
# some additional paths
#
export PATH="$PATH:$WORK/rebar3"

#
# man
#
export MANPATH="/usr/share/man/:/usr/local/pgsql/share/man/:$DEV/postgres/doc/src/sgml"
