#!/bin/bash

# some additional PATHS
export PATH=$PATH:$HOME/bin

# Some python tweaks
export PYTHONSTARTUP=~/.pythonrc

# ocaml
export PATH=$PATH:$HOME/.opam/default/bin
test -r /home/alex/.opam/opam-init/init.sh && . /home/alex/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

export PATH=$PATH:/usr/lib/jvm/java-1.8.0/bin
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$WORK/elixir/bin
export PATH=$PATH:/usr/local/pgsql/bin/
export PATH=$PATH:/home/alex/disk2/mysql/bin
test -d ${DEV_DISK}/etcd/bin && export PATH=$PATH:$DEV_DISK/etcd/bin
test -d /usr/local/mysql/bin && export PATH=$PATH:/usr/local/mysql/bin
test -d /usr/local/mysql/scripts && export PATH=$PATH:/usr/local/mysql/scripts
test -d ${DEV_DISK}/db/usr/local/mysql/bin && export PATH=$PATH:${DEV_DISK}/db/usr/local/mysql/bin
test -d ${DEV_DISK}/db/usr/local/mysql/scripts && export PATH=$PATH:${DEV_DISK}/db/usr/local/mysql/scripts
test -d ${HOME}/.local/zed.app/bin && export PATH=$PATH:${HOME}.local/zed.app/bin
test -d /snap/k9s && export PATH=$PATH:/snap/k9s/current/bin
test -d $HOME/.cache/rebar3/bin && export PATH=$PATH:/home/alex/.cache/rebar3/bin
test -d $HOME/.krew/bin && export PATH=$HOME/.krew/bin:$PATH
test -d $HOME/.nvm && export NVM_DIR="$HOME/.nvm"
test -s $NVM_DIR/nvm.sh && \. "$NVM_DIR/nvm.sh"
test -s $NVM_DIR/bash_completion && \. "$NVM_DIR/bash_completion"

# add zig and zls to PATH
test -e ${DEV_DISK}/zig/zig && export PATH=$PATH:${DEV_DISK}/zig
test -e ${DEV_DISK}/zls/zls && export PATH=$PATH:${DEV_DISK}/zls

# Linker options
export LD_LIBRARY_PATH=""
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/"
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu

# Kernel and C dev, systemd
export PATH=$PATH:$KERNEL_DEV/tools/perf/
export PATH=$PATH:/usr/lib/systemd/

# golang
export GOPATH=/usr/local/bin/go
export PATH=$PATH:$GOPATH/bin

# less
export LESSHISTFILE="/dev/null"

# man
export MANPATH="/usr/share/man/:/usr/local/pgsql/share/man/:$DEV/postgres/doc/src/sgml"
export MANPATH=$MANPATH:/usr/local/share/man

# docker options
export DOCKER_STORAGE_OPTIONS="overlay"

# path to SSL certs
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt

# virtual machines
export VAGRANT_HOME=/home/alex/disk2/.vagrant.d/

# Path to android sdk
export ANDROID_SDK_HOME=/home/alex/disk/dev/.android
