#!/bin/bash

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='xterm-256color';
fi;

if [[ -n "$TMUX" ]]
then
    export TERM="screen-256color"
fi

PS1='\w$(__git_ps1 " \[\e[1;34m\](%s) ")\[\e[0m\]\$ '

#
# one of the best standard prompt for git
#
source ~/bin/git-prompt/.git-prompt.sh

