#!/bin/bash

# awk
alias awk="gawk --optimize"

# reload ~/.bashrc
alias reloadBash="source ~/.bashrc"
# always copy recursively
alias cp='cp -r '
# mkdir
alias mkdir="mkdir -p"
# rm
alias rm="rm -rf -i"
alias rmi="rm -rf --interactive"

# navigation
alias work='cd $WORK'
alias dev='cd  $DEV'
alias home='cd $HOME'
alias oldhome='cd $OLD_HDD'
alias downloads="cd $OLD_HDD/Downloads"
alias golang="cd $DEV/golang/src/github.com/0xAX"
alias linux="cd $DEV/linux"

# navigation by configs
alias bashrc="cd ~ && emacs -nw .bashrc"
alias gitconfig="cd ~ && emacs -nw .gitconfig"
alias gitignore_global="cd ~ && emacs -nw .global_gitignore"
alias sshconfig="cd ~ && emacs -nw .ssh/config"
alias i3config="cd ~ && emacs -nw .i3/config"
alias mail_config="cd ~ && emacs -nw .muttrc"

# open applications
alias books="nautilus $OLD_HDD/books"
alias downloads="nautilus $OLD_HDD/Downloads"
alias important="nautilus $OLD_HDD/important"
alias menu="linux && make menuconfig"
alias read_book="evince &"

# open web resource
alias twitter="firefox -new-tab twitter.com"
alias github="firefox -new-tab github.com"
alias google="firefox -new-tab google.com"
alias gmail="firefox -new-tab gmail.com"
alias reddit="firefox -new-tab reddit.com"
alias kproxy="firefox -new-tab kproxy"

# mount and umount
alias m="mount -t "
alias um="umount -t "

# dpkg
alias packageInstall="dpkg -i "
alias packageList="dpkg -l"
alias packageCheck="dpkg -s"
alias packageLocate="dpkg -L "

# df
alias df="df -h"

# du
alias dirsize="du -sh "
alias filesize="du -s "

# find
alias find_everywhere_name="sudo find / -name "
alias find_everywhere_type="sudo find / -type "
alias find_here_name="find . -name "
alias find_here_type="find . -type "

# copy/paste
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# apt and aptitude
alias apt-install="sudo apt-get install "
alias apt-remove="sudo apt-get purge "
alias apt-update="sudo apt-get update "
alias apt-upgrade="sudo apt-get upgrade "
alias apt-urls="sudo nano /etc/apt/sources.list "
alias apt-packages="sudo apt-cache pkgnames "
alias apt-search="sudo apt-cache search "
alias apt-info="sudo apt-cache show "
alias apt-clean="sudo apt-get clean"
alias apt-check="sudo apt-get check"
alias apt-auto-clean="sudo apt-get autoclean"
alias apt-auto-remove="sudo apt-get autoremove"
alias apt-pkg-version="sudo aptitude versions "

# wc
alias lines="wc -l "
alias words="wc -w "
alias bytes="wc -c "
alias chars="wc -m "

# date
alias week='date +%V'
alias day='date +%A'
alias monthNum='date +%d'
alias dayNum='date +%e'
alias month="date +%B"

# clear
alias cl='clear'

# tmux
alias tmux-new='tmux new -s '
alias tmux-list='tmux ls'
alias tmux-old-session='tmux attach -t '
alias tmux-kill='tmux kill-session -t '

# mail
alias mutt-help="firefox http://sheet.shiar.nl/mutt"

# nano
alias nano=vim

# i3 related aliases
alias i3-restart="i3-msg restart"

# pacman
alias pac-update="sudo pacman -Suy"

# terminator
alias terminator="terminator --profile=alex "

#
# docker
#
function DockerRemoveImgs() {
    docker rmi $(docker images -q) $@
}

function DockerRemoveContainers() {
    docker rm $(docker ps -a -q) $@
}

function DockerInstall() {
    sudo cp -r /home/alex/dev/docker/bundles/latest/binary-daemon/docker* /usr/bin
    sudo cp -r /home/alex/dev/docker/bundles/latest/binary-client/docker-1.13.0-dev /usr/bin
    sudo mv /usr/bin/docker-1.13.0-dev /usr/bin/docker
}

function DockerRemoveUntagedImages() {
    docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
}

function DockerMySqlWorkRun() {
    docker run -d -p 3306:3306 --name=mysql-work -e MYSQL_ALLOW_EMPTY_PASSWORD=true mariadb:10
}

function DockerMysqlFromTrunk() {
    docker run -d -p 3306:3306 --name=mysql-8 -e MYSQL_ALLOW_EMPTY_PASSWORD=true mysql:8
}

function DockerMySqlWorkStart() {
    docker start mysql-work
}

alias docker-install=DockerInstall
alias docker-remove-imgs=DockerRemoveImgs
alias docker-remove-containers=DockerRemoveContainers
alias docker-daemon="sudo docker daemon --storage-driver=overlay --log-driver=journald"
alias docker-remove-untaged-images=DockerRemoveUntagedImages
alias docker-mysql-work-run=DockerMySqlWorkRun
alias docker-mysql-work-start=DockerMySqlWorkStart
alias docker-mysql-trunk-run=DockerMysqlFromTrunk

#
# Join into coreos
#
alias coreos-join="ssh -l core -p 2222 localhost"
