#!/bin/bash

# awk aliaease
alias awk="gawk --optimize"

# cp aliases
alias cp='cp -r '

# mkdir aliases
alias mkdir="mkdir -p"

# rm aliases
alias rm="rm -rf -i"
alias rmi="rm -rf --interactive"

# reload ~/.bashrc
alias reloadBash="source ~/.bashrc"

# navigation
alias work='cd $WORK'
alias dev='cd  $DEV'
alias home='cd $HOME'
alias oldhome='cd $OLD_HDD'
alias downloads="cd $OLD_HDD/Downloads"
alias golang="cd $DEV/golang/src/github.com/0xAX"
alias linux="cd $DEV/linux"
alias disk='cd ${DISK}'

# navigation by configs
alias bashrc="cd ~ && emacs -nw .bashrc"
alias gitconfig="cd ~ && emacs -nw .gitconfig"
alias gitignore_global="cd ~ && emacs -nw .global_gitignore"
alias sshconfig="cd ~ && emacs -nw .ssh/config"
alias i3config="cd ~ && emacs -nw .i3/config"
alias mail_config="cd ~ && emacs -nw .muttrc"

# open applications
alias books="nautilus $OLD_HDD/books"
alias downloads="nautilus $OLD_HDD/Downloads"
alias important="nautilus $OLD_HDD/important"
alias menu="linux && make menuconfig"
alias read_book="evince &"

# open web resource
alias twitter="firefox -new-tab twitter.com"
alias github="firefox -new-tab github.com"
alias google="firefox -new-tab google.com"
alias gmail="firefox -new-tab gmail.com"
alias reddit="firefox -new-tab reddit.com"
alias kproxy="firefox -new-tab kproxy"

# mount and umount
alias m="mount -t "
alias um="umount -t "

# dpkg
alias packageInstall="dpkg -i "
alias packageList="dpkg -l"
alias packageCheck="dpkg -s"
alias packageLocate="dpkg -L "

# df
alias df="df -h"

# du
alias dirsize="du -sh "
alias filesize="du -s "

# find
alias find_everywhere_name="sudo find / -name "
alias find_everywhere_type="sudo find / -type "
alias find_here_name="find . -name "
alias find_here_type="find . -type "

# copy/paste
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# wc
alias lines="wc -l "
alias words="wc -w "
alias bytes="wc -c "
alias chars="wc -m "

# date
alias week='date +%V'
alias day='date +%A'
alias monthNum='date +%d'
alias dayNum='date +%e'
alias month="date +%B"
alias timestamp="date +%s"

# clear
alias cl='clear'

# tmux
alias tmux-new='tmux new -s '
alias tmux-list='tmux ls'
alias tmux-old-session='tmux attach -t '
alias tmux-kill='tmux kill-session -t '

# mail
alias mutt-help="firefox http://sheet.shiar.nl/mutt"

# nano
alias nano=vim

# i3 related aliases
alias i3-restart="i3-msg restart"

# terminator
alias terminator="terminator --profile=alex "

# other aliases related to mysql
alias kill-mysql="pkill mysql"

# Linux kernel
alias save-kernel-config="cp -r $DEV/linux/.config $DOTFILES/linux-dev/x86_64_conf/"

# start ercdf with default configuration
alias ercdf-start="rebar3 shell --config config/ercdf.config"

# i3 aliases
alias i3-restart="i3-msg restart"

# erlang dev
alias runerl="BINDIR=/home/alex/disk/dev/otp/bin/x86_64-pc-linux-gnu ./bin/x86_64-pc-linux-gnu/erlexec"
alias builderl="cd /home/alex/dev/otp && ./otp_build all"
alias otp_23_activate=". /home/alex/dev/otp-23/activate"
alias otp_24_activate=". /home/alex/dev/otp-24/activate"

# nightly browser
alias browser-nightly-run-directly="./obj-x86_64-pc-linux-gnu/dist/bin/firefox --MOZ_LOG=\"gParserLog:5\""
alias browser-nightly-run="MACH_USE_SYSTEM_PYTHON=1 ./mach run"
alias browser-nightly-build="MACH_USE_SYSTEM_PYTHON=1 ./mach build"

# jumphosts
alias tp-proxy-up='ssh -fNTMD 8080 jump'
alias tp-proxy-status='ssh -TO check jump'
alias tp-proxy-down='ssh -TO exit jump'

# run vm for work
alias run-ubuntu-vm='qemu-kvm -m 6G -vga virtio -display default,show-cursor=on -smp 2 -drive file=ubuntu-desktop-18.04.qcow2,if=virtio -net user,hostfwd=tcp::10022-:22 -net nic'

# work related aliases
alias enable-pcs-cache='export PCS_STORAGE=mysql; export CACHE_SESSIONS=true;'
alias disable-pcs-cache='unset PCS_STORAGE; unset CACHE_SESSIONS;'
alias enable-pcs-mysql='export PCS_STORAGE=mysql; unset CACHE_SESSIONS;'
