#!/bin/bash

# if we're starting system manually via startx the DISPLAY env variable might be
# not set.

XDG_SESSION_VAL=$(loginctl show-session "$XDG_SESSION_ID" -p Type)

if [[ "$XDG_SESSION_VAL"  = "Type=x11" ]] ; then
    if [ ! -z "$DISPLAY" ];
    then
        FEH=$(whereis feh | awk '{print $2}')

        if [ ! -z "$FEH" ]
        then
            $FEH --bg-scale "$HOME/dev/dotfiles/wallpapers/solarized-dark-wallpaper.jpg"
        fi
    fi
fi
