#!/bin/bash

if ! command -v op &> /dev/null
then
    echo "Error: op command not found" 1>&2
    exit 1
fi

if ! command -v neomutt &> /dev/null
then
    echo "Error: neomutt command not found" 1>&2
    exit 1
fi

eval $(op signin)

neomutt -F ~/.neomutrc

exit 0;
