#!/bin/bash

if ! command -v op &> /dev/null
then
    echo "Error: op command not found" 1>&2
    exit 1
fi

if ! command -v offlineimap &> /dev/null
then
    echo "Error: offlineimap command not found" 1>&2
    exit 1
fi

eval $(op signin)

offlineimap

exit 0;
